In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

df = pd.read_csv('diabetes.csv')
df.head()

In [ ]:
df.info()

In [ ]:
Y = df.iloc[:,-1]
X = df.drop(['Outcome'],axis=1)
X.head()

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
X_train,X_val,y_train,y_val = train_test_split(X,Y,test_size=0.25,random_state=0)
lr.fit(X_train,y_train)
y1=lr.predict(X_val)

In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_val,y1))
print(metrics.classification_report(y_val,y1))


In [ ]:
#decision tree
Y = df.iloc[:,-1]
X = df.drop(['Outcome'],axis=1)


In [ ]:
from sklearn.tree import DecisionTreeClassifier
from sklearn.model_selection import cross_val_score
from sklearn import metrics
clf = DecisionTreeClassifier(random_state=0)
clf.fit(X_train,y_train)
y1=clf.predict(X_val)
y1

In [ ]:
metrics.accuracy_score(y_val,y1)
confusion_matrix(y_val,y1)

array([[102,  28],
       [ 26,  36]])

In [ ]:
print(metrics.classification_report(y_val,y1))

In [ ]:
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
Y = df.iloc[:,-1]
X = df.drop(['Outcome'],axis=1)

In [ ]:
clf = make_pipeline(StandardScaler(),SVC(gamma='auto'))
clf.fit(X_train,y_train)
y1=clf.predict(X_val)
confusion_matrix(y_val,y1)

array([[117,  13],
       [ 30,  32]])

In [ ]:
print(metrics.classification_report(y_val,y1))

              precision    recall  f1-score   support

           0       0.80      0.90      0.84       130
           1       0.71      0.52      0.60        62

    accuracy                           0.78       192
   macro avg       0.75      0.71      0.72       192
weighted avg       0.77      0.78      0.77       192



In [ ]:
from sklearn.naive_bayes import GaussianNB
gnb=GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_val)
confusion_matrix(y_val,y_pred)

array([[114,  16],
       [ 29,  33]])

In [ ]:
print(metrics.classification_report(y_val,y_pred))

              precision    recall  f1-score   support

           0       0.80      0.88      0.84       130
           1       0.67      0.53      0.59        62

    accuracy                           0.77       192
   macro avg       0.74      0.70      0.71       192
weighted avg       0.76      0.77      0.76       192



In [ ]:
df = pd.read_csv('apples_and_oranges.csv')
df.head()

Weight  Size   Class
0      69  4.39  orange
1      69  4.21  orange
2      65  4.09  orange
3      72  5.85   apple
4      67  4.70  orange

In [ ]:
from sklearn.preprocessing import OneHotEncoder
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()
dfle=df
dfle.Class = le.fit_transform(dfle.Class)
dfle 

Weight  Size  Class
0       69  4.39      1
1       69  4.21      1
2       65  4.09      1
3       72  5.85      0
4       67  4.70      1
5       73  5.68      0
6       70  5.56      0
7       75  5.11      0
8       74  5.36      0
9       65  4.27      1
10      73  5.79      0
11      70  5.47      0
12      74  5.53      0
13      68  4.47      1
14      74  5.22      0
15      65  4.48      1
16      69  4.66      1
17      75  5.25      0
18      67  4.18      1
19      74  5.50      0
20      66  4.13      1
21      70  4.83      1
22      69  4.61      1
23      68  4.08      1
24      67  4.25      1
25      71  5.35      0
26      67  4.01      1
27      70  4.22      1
28      74  5.25      0
29      71  5.26      0
30      73  5.78      0
31      66  4.68      1
32      72  5.72      0
33      73  5.17      0
34      68  4.83      1
35      69  4.11      1
36      69  4.76      1
37      74  5.48      0
38      70  5.59      0
39      73  5.03      0

In [ ]:
Y = dfle.iloc[:,-1]
X = dfle.drop(['Class'],axis=1)
Y

0     1
1     1
2     1
3     0
4     1
5     0
6     0
7     0
8     0
9     1
10    0
11    0
12    0
13    1
14    0
15    1
16    1
17    0
18    1
19    0
20    1
21    1
22    1
23    1
24    1
25    0
26    1
27    1
28    0
29    0
30    0
31    1
32    0
33    0
34    1
35    1
36    1
37    0
38    0
39    0
Name: Class, dtype: int64

In [ ]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression()
X_train,X_val,y_train,y_val = train_test_split(X,Y,test_size=0.25,random_state=0)
lr.fit(X_train,y_train)
y1=lr.predict(X_val)

In [ ]:
from sklearn.metrics import confusion_matrix
print(confusion_matrix(y_val,y1))
print(metrics.classification_report(y_val,y1))

[[5 0]
 [0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         5

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10



In [ ]:
clf = DecisionTreeClassifier(random_state=0)
clf.fit(X_train,y_train)
y1=clf.predict(X_val)
print(confusion_matrix(y_val,y1))
print(metrics.classification_report(y_val,y1))

[[5 0]
 [0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         5

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10



In [ ]:
clf = make_pipeline(StandardScaler(),SVC(gamma='auto'))
clf.fit(X_train,y_train)
y1=clf.predict(X_val)
print(confusion_matrix(y_val,y1))
print(metrics.classification_report(y_val,y1))


[[5 0]
 [0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         5

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10



In [ ]:
gnb=GaussianNB()
y_pred = gnb.fit(X_train, y_train).predict(X_val)
print(confusion_matrix(y_val,y_pred))
print(metrics.classification_report(y_val,y_pred))

[[5 0]
 [0 5]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         5
           1       1.00      1.00      1.00         5

    accuracy                           1.00        10
   macro avg       1.00      1.00      1.00        10
weighted avg       1.00      1.00      1.00        10

